export const SearchItemData=[
    {
        Id:1,
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Title:'Khwaja Fareed University of Engineering and Information Technology',
        City:'Rahim Yar Khan',
        Status:'Goverment',
        Location:'Abu Dhabi Rd, Rahim Yar Khan, Punjab',
        Price:'CHF 3.60 /day',
        MeetingPoint:'Meeting Point: Rolex Learning Center, 1015 Ecublens, Suisse',
        Description:'This headset offers ultimate comfort for prolonged gaming sessions through its low weight and noise reducing closed ear cups using soft comfortable signature memory foam with a highly adjustable headband for a perfect fit. Crystal clear sound and excellent noise isolation bring you a total immersion into your gaming session.',
    },
    {
        Id:2,
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Title:'Khwaja Fareed University of Engineering and Information Technology',
        City:'Rahim Yar Khan',
        Status:'Goverment',
        Location:'Abu Dhabi Rd, Rahim Yar Khan, Punjab',
        Price:'CHF 3.60 /day',
        MeetingPoint:'Meeting Point: Rolex Learning Center, 1015 Ecublens, Suisse',
        Description:'This headset offers ultimate comfort for prolonged gaming sessions through its low weight and noise reducing closed ear cups using soft comfortable signature memory foam with a highly adjustable headband for a perfect fit. Crystal clear sound and excellent noise isolation bring you a total immersion into your gaming session.',
    },
    {
        Id:3,
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Title:'Khwaja Fareed University of Engineering and Information Technology',
        City:'Rahim Yar Khan',
        Status:'Goverment',
        Location:'Abu Dhabi Rd, Rahim Yar Khan, Punjab',
        Price:'CHF 3.60 /day',
        MeetingPoint:'Meeting Point: Rolex Learning Center, 1015 Ecublens, Suisse',
        Description:'This headset offers ultimate comfort for prolonged gaming sessions through its low weight and noise reducing closed ear cups using soft comfortable signature memory foam with a highly adjustable headband for a perfect fit. Crystal clear sound and excellent noise isolation bring you a total immersion into your gaming session.',
    },
    {
        Id:4,
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Image1:require('../../../Assets/Images/university.png'),
        Title:'Khwaja Fareed University of Engineering and Information Technology',
        City:'Rahim Yar Khan',
        Status:'Goverment',
        Location:'Abu Dhabi Rd, Rahim Yar Khan, Punjab',
        Price:'CHF 3.60 /day',
        MeetingPoint:'Meeting Point: Rolex Learning Center, 1015 Ecublens, Suisse',
        Description:'This headset offers ultimate comfort for prolonged gaming sessions through its low weight and noise reducing closed ear cups using soft comfortable signature memory foam with a highly adjustable headband for a perfect fit. Crystal clear sound and excellent noise isolation bring you a total immersion into your gaming session.',
    },
]